### ISSUE TITLE
Fails to set Tracing when a custom function name is used

### ISSUE THREAD

**Issue by steve-exley** [AlexanderMS/serverless-plugin-tracing#3]
Nice plugin. There is a small issue that occurs when a custom name element is used with the serverless functions. In this scenario, Tracing is not set.

It should be a pretty easy fix to check for the 'name' element before calling toggleTracing. Something like:

this.toggleTracing((
        service.functions[functionName].name ||
        `${service.service}-${stage}-${functionName}`),
          (service.functions[functionName].tracing === true)
          || (providerLevelTracingEnabled && service.functions[functionName].tracing !== false)
        );

Thanks

**Comment by AlexanderMS** [comment]
Thanks! Added in `serverless-plugin-tracing@1.0.6`
